// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/10/27 下午6:31:23
const configMerger = require("D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/plugins/**/*.{js,ts,mjs}","D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/composables/**/*.{js,ts,mjs}","D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/utils/**/*.{js,ts,mjs}","D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/小可愛學架網站/node_test/jeby_website/my-nuxt-project/app.config.{js,ts,mjs}"] } }));

module.exports = config
